name: D-Installer workflow

jobs:
  dinstaller:
    container:
      image: registry.opensuse.org/yast/head/containers/containers_tumbleweed/opensuse/dinstaller-web
      volumes:
        - dbus_run:/var/run/dbus
    services:
      backend:
        image: registry.opensuse.org/yast/head/containers/containers_tumbleweed/opensuse/dinstaller-backend
        volumes:
          - dbus_run:/var/run/dbus
